### ISSUE TITLE
Logic Requests

### ISSUE THREAD

**Issue by kobrien603** [VictorBezak/Plotly_Multi-Axes_Gridlines#3]
Hello,

Would it be possible to extend this formula to support just finding the dticks between the y1 and y2 without returning the newly formulated y1 & y2 min max?

I have requests where a user wants a specific range to show on the chart for y1 and y2 but still have the ticks line up. 

At the moment, if I don't apply the new formulated y1 and y2 ranges, the dticks calculated will not line up.

I'm not a math major and have tried to review the formula but ultimately can't figure it out. Hoping you could help me out.

Any questions or concerns please let me know.

Thanks,

Kieran

**Comment by VictorBezak** [comment]
So glad to hear from you, I'd be happy to take a look at this over the weekend. If you'd be interested in collaborating on this, we could schedule a working session over the weekend, or if you'd rather enjoy your weekend, I'm happy to solo explore this!
Just let me know, otherwise, I'll get back to you as soon as I have results or follow-up questions.

**Comment by kobrien603** [comment]
I'd love to try to help but as it's Easter weekend I will be away from the computer. I am more available next week if you'd like? Otherwise, if you want to take a crack at it this weekend, all you!

I will quickly build a sample project and post it here to help with the request.

**Comment by kobrien603** [comment]
I built a quick example that uses your tick formula while also requesting user input for min and max. 

Let me know if you have any questions!

https://github.com/kobrien603/PlotlyFixTicks

**Comment by VictorBezak** [comment]
Love that you threw together a sample project to work with, thanks for that. Doesn't look like I'm going to reach a solution tonight. I'll come back to it during the week if I find time, but I usually work until late. If you have time and interest just let me know and we can plug-in together one of these evenings or next weekend!!

**Comment by VictorBezak** [comment]
Yeah this will be an interesting problem. I look forward to spending more time thinking about it.

**Comment by VictorBezak** [comment]
@kobrien603 I refactored the code into a module to make the implementation a little more simple. I don't believe this accomplishes what you were asking for, but it does break things up in a way that will make it easier to test and modify.

The new code is pushed onto a separate branch -- the "module" branch. Please take a look and let me know if this is easier for you to work with and provide me any feedback you can so that I can complete this next weekend for you.

The only important files will be:
    - src/grid-sync.js (the module which handles the logic)
    - src/index.js (the implementation)

**Comment by kobrien603** [comment]
@VictorBezak Thank you! Sorry for the late response. Busy with life. I will take a look at it this weekend.

**Comment by JonathanShrek** [comment]
Any new updates on this? This feature would be super helpful.

**Comment by VictorBezak** [comment]
@JonathanShrek yes, actually! Put in a open-source PR yesterday with the help of another dev and we're hoping to hear back from the plotly team soon with some feedback. https://github.com/plotly/plotly.js/pull/6356

**Comment by VictorBezak** [comment]
@JonathanShrek closing this issue, please let me know if you'd like help implementing this natively, as the new tickmode option `sync` was release in v`2.18.0`! 

PR: https://github.com/plotly/plotly.js/pull/6356
Release Notes: https://github.com/plotly/plotly.js/releases/tag/v2.18.0
